package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApplicationServerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationServerAllPropertiesEquals(ApplicationServer expected, ApplicationServer actual) {
        assertApplicationServerAutoGeneratedPropertiesEquals(expected, actual);
        assertApplicationServerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationServerAllUpdatablePropertiesEquals(ApplicationServer expected, ApplicationServer actual) {
        assertApplicationServerUpdatableFieldsEquals(expected, actual);
        assertApplicationServerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationServerAutoGeneratedPropertiesEquals(ApplicationServer expected, ApplicationServer actual) {
        assertThat(actual)
            .as("Verify ApplicationServer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationServerUpdatableFieldsEquals(ApplicationServer expected, ApplicationServer actual) {
        assertThat(actual)
            .as("Verify ApplicationServer relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreaDate()).as("check creaDate").isEqualTo(expected.getCreaDate()))
            .satisfies(a -> assertThat(a.getUpdateDate()).as("check updateDate").isEqualTo(expected.getUpdateDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationServerUpdatableRelationshipsEquals(ApplicationServer expected, ApplicationServer actual) {
        // empty method
    }
}
