package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DBAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBAllPropertiesEquals(DB expected, DB actual) {
        assertDBAutoGeneratedPropertiesEquals(expected, actual);
        assertDBAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBAllUpdatablePropertiesEquals(DB expected, DB actual) {
        assertDBUpdatableFieldsEquals(expected, actual);
        assertDBUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBAutoGeneratedPropertiesEquals(DB expected, DB actual) {
        assertThat(actual)
            .as("Verify DB auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBUpdatableFieldsEquals(DB expected, DB actual) {
        assertThat(actual)
            .as("Verify DB relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreaDate()).as("check creaDate").isEqualTo(expected.getCreaDate()))
            .satisfies(a -> assertThat(a.getUpdateDate()).as("check updateDate").isEqualTo(expected.getUpdateDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBUpdatableRelationshipsEquals(DB expected, DB actual) {
        // empty method
    }
}
