package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HOSTAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHOSTAllPropertiesEquals(HOST expected, HOST actual) {
        assertHOSTAutoGeneratedPropertiesEquals(expected, actual);
        assertHOSTAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHOSTAllUpdatablePropertiesEquals(HOST expected, HOST actual) {
        assertHOSTUpdatableFieldsEquals(expected, actual);
        assertHOSTUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHOSTAutoGeneratedPropertiesEquals(HOST expected, HOST actual) {
        assertThat(actual)
            .as("Verify HOST auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHOSTUpdatableFieldsEquals(HOST expected, HOST actual) {
        assertThat(actual)
            .as("Verify HOST relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreaDate()).as("check creaDate").isEqualTo(expected.getCreaDate()))
            .satisfies(a -> assertThat(a.getUpdateDate()).as("check updateDate").isEqualTo(expected.getUpdateDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHOSTUpdatableRelationshipsEquals(HOST expected, HOST actual) {
        // empty method
    }
}
