package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HSMAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHSMAllPropertiesEquals(HSM expected, HSM actual) {
        assertHSMAutoGeneratedPropertiesEquals(expected, actual);
        assertHSMAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHSMAllUpdatablePropertiesEquals(HSM expected, HSM actual) {
        assertHSMUpdatableFieldsEquals(expected, actual);
        assertHSMUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHSMAutoGeneratedPropertiesEquals(HSM expected, HSM actual) {
        assertThat(actual)
            .as("Verify HSM auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHSMUpdatableFieldsEquals(HSM expected, HSM actual) {
        assertThat(actual)
            .as("Verify HSM relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreaDate()).as("check creaDate").isEqualTo(expected.getCreaDate()))
            .satisfies(a -> assertThat(a.getUpdateDate()).as("check updateDate").isEqualTo(expected.getUpdateDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHSMUpdatableRelationshipsEquals(HSM expected, HSM actual) {
        // empty method
    }
}
