package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OSAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOSAllPropertiesEquals(OS expected, OS actual) {
        assertOSAutoGeneratedPropertiesEquals(expected, actual);
        assertOSAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOSAllUpdatablePropertiesEquals(OS expected, OS actual) {
        assertOSUpdatableFieldsEquals(expected, actual);
        assertOSUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOSAutoGeneratedPropertiesEquals(OS expected, OS actual) {
        assertThat(actual)
            .as("Verify OS auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOSUpdatableFieldsEquals(OS expected, OS actual) {
        assertThat(actual)
            .as("Verify OS relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreaDate()).as("check creaDate").isEqualTo(expected.getCreaDate()))
            .satisfies(a -> assertThat(a.getUpdateDate()).as("check updateDate").isEqualTo(expected.getUpdateDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOSUpdatableRelationshipsEquals(OS expected, OS actual) {
        // empty method
    }
}
